baseURL = "https://github.com/xcl0416/greatgroup"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "docs"
theme = "LeaveIt"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4